---
- name: Deploy war file from tomcat
  get_url: 
    url: http://192.168.0.10:8081/nexus/content/repositories/snapshots/org/springframework/boot/spring-boot-samples/1.4.0.BUILD-SNAPSHOT/*.war
    dest: {{ TOMCAT_HOME }}/webapps/petclinic.war
    url_username: "{{ NEXUS_USER }}"
    url_password: "{{ NEXUS_PASS }}"
    validate_certs: no
